(insert! 'start 'p1 3 my-table)
(insert! 'p0 'p1 2 my-table)
(insert! 'start 'p2 7 my-table)
(insert! 'p1 'p2 1 my-table)
(insert! 'p2 'end 11 my-table)
(insert! 'p2 'p3 1 my-table)
(insert! 'p5 'p6 3 my-table)
(insert! 'p1 'end 22 my-table)
